// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1M9DvtfB_0dYtbBuOhBgaFOqzk3SeeQM',
    appId: '1:874999479733:web:00978ad6ff3cbdd795adfc',
    messagingSenderId: '874999479733',
    projectId: 'ktmhostelpluee',
    authDomain: 'ktmhostelpluee.firebaseapp.com',
    storageBucket: 'ktmhostelpluee.firebasestorage.app',
    measurementId: 'G-CGD5GXLG7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfzD_jn1A6OG-Bl1SP-A4iPDF_syfzqg',
    appId: '1:874999479733:android:3d7bd9a0801f0a1b95adfc',
    messagingSenderId: '874999479733',
    projectId: 'ktmhostelpluee',
    storageBucket: 'ktmhostelpluee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApl-jhPH3mczXYuU2I2czJo2u6jC9apLk',
    appId: '1:874999479733:ios:0011e8828ebcb0d595adfc',
    messagingSenderId: '874999479733',
    projectId: 'ktmhostelpluee',
    storageBucket: 'ktmhostelpluee.firebasestorage.app',
    iosBundleId: 'com.kathmadnuhostelapp.kathmadnuhostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApl-jhPH3mczXYuU2I2czJo2u6jC9apLk',
    appId: '1:874999479733:ios:0011e8828ebcb0d595adfc',
    messagingSenderId: '874999479733',
    projectId: 'ktmhostelpluee',
    storageBucket: 'ktmhostelpluee.firebasestorage.app',
    iosBundleId: 'com.kathmadnuhostelapp.kathmadnuhostel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1M9DvtfB_0dYtbBuOhBgaFOqzk3SeeQM',
    appId: '1:874999479733:web:481a5743538816de95adfc',
    messagingSenderId: '874999479733',
    projectId: 'ktmhostelpluee',
    authDomain: 'ktmhostelpluee.firebaseapp.com',
    storageBucket: 'ktmhostelpluee.firebasestorage.app',
    measurementId: 'G-F9EKQEVG66',
  );
}
